require "#{File.dirname(__FILE__)}/../../../../src/components/core/chef/Berksfile.core"

gusztavvargadr_sources

cookbook 'gusztavvargadr_octopus_server', path: '../chef/cookbooks/gusztavvargadr_octopus_server'

gusztavvargadr_cookbook 'components', 'octopus'
gusztavvargadr_cookbook 'components', 'windows'
