require "#{File.dirname(__FILE__)}/../../../Vagrantfile.core"
require "#{File.dirname(__FILE__)}/../../../../src/components/octopus/vagrant/Vagrantfile.core"

Environment.defaults(
  octopus: {
    server: {
      hostname: '',
      api_key: 'API-6ENORPWQM3NWT7G6P47W5USM',
      thumbprint: '72D090FFBAD730D24084D9E68691E782ADBAAC4C',
    },
    tentacle: {
      environment_names: ['test'],
      tenant_names: ['private'],
    },
  }
)

Environment.new(name: 'octopus.local') do |environment|
  VM.new(environment, name: 'server', box: 'gusztavvargadr/w16s-sql14d') do |server|
    WindowsSample.new(server)

    server.vagrant.vm.synced_folder "#{File.dirname(__FILE__)}/../data", '/vagrant-data'

    OctopusServer.new(
      server,
      chef_json: {
        'gusztavvargadr_octopus' => {
          'server' => {
            'import' => {
              'C:\\vagrant-data\\server\\core' => {
                'password' => 'Octopus42',
              },
              'C:\\vagrant-data\\server\\vagrant' => {
                'password' => 'Octopus42',
              },
            },
          },
        },
      }
    )
  end

  VM.new(environment, name: 'tentacle', box: 'gusztavvargadr/w16s') do |tentacle|
    WindowsSample.new(tentacle)

    OctopusTentacle.new(
      tentacle,
      chef_json: {
        'gusztavvargadr_octopus' => {
          'tentacle' => {
            'role_names' => ['tentacle'],
          },
        },
      }
    )
  end
end
