require "#{File.dirname(__FILE__)}/../../../Vagrantfile.core"

Environment.new(name: 'dotnet.local') do |environment|
  VM.new(environment, name: 'core', box: 'gusztavvargadr/w16s-iis') do |core|
    WindowsSample.new(core)

    core.vagrant.vm.synced_folder "#{File.dirname(__FILE__)}/..", '/vagrant-parent'

    ShellProvisioner.new(core, inline: 'choco install -y dotnetcore-windowshosting')
    ShellProvisioner.new(core, inline: 'choco install -y dotnetcore-sdk')
    ShellProvisioner.new(core, inline: 'iisreset')
    ShellProvisioner.new(core, inline: 'choco install -y octopustools')
  end
end
