---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../core/chef/Vagrantfile.kitchen
  synced_folders:
    - ["test", "/tmp/kitchen/test"]

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w16s
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s-sql14d

suites:
  - name: client
    run_list:
      - recipe[gusztavvargadr_octopus::client]
  - name: server
    run_list:
      - recipe[gusztavvargadr_octopus::server]
    attributes:
      gusztavvargadr_octopus:
        server:
          execute_username: vagrant
          execute_password: vagrant
          web_username: vagrant
          web_password: Vagrant42
          import:
            C:\\tmp\\kitchen\\test\\integration\\server\\core:
              password: Vagrant42
  - name: tentacle-polling
    run_list:
      - recipe[gusztavvargadr_octopus::server]
      - recipe[gusztavvargadr_octopus::tentacle]
    attributes:
      gusztavvargadr_octopus:
        server:
          execute_username: vagrant
          execute_password: vagrant
          web_username: vagrant
          web_password: Vagrant42
          import:
            C:\\tmp\\kitchen\\test\\integration\\server\\core:
              password: Vagrant42
        tentacle:
          execute_username: vagrant
          execute_password: vagrant
          server_api_key: API-6ENORPWQM3NWT7G6P47W5USM
          environment_names:
            - environment
          tenant_names:
            - tenant
          role_names:
            - polling
  - name: tentacle-listening
    run_list:
      - recipe[gusztavvargadr_octopus::server]
      - recipe[gusztavvargadr_octopus::tentacle]
    attributes:
      gusztavvargadr_octopus:
        server:
          execute_username: vagrant
          execute_password: vagrant
          web_username: vagrant
          web_password: Vagrant42
          import:
            C:\\tmp\\kitchen\\test\\integration\\server\\core:
              password: Vagrant42
        tentacle:
          execute_username: vagrant
          execute_password: vagrant
          server_api_key: API-6ENORPWQM3NWT7G6P47W5USM
          server_thumbprint: 96195237FCE647FFE277DE7CE749264AC65DAFFF
          environment_names:
            - environment
          tenant_names:
            - tenant
          role_names:
            - listening
