require "#{File.dirname(__FILE__)}/../../../Vagrantfile.core"

Environment.new(name: 'sql.local') do |environment|
  WindowsSampleVM.new(environment, name: '14d', box: 'gusztavvargadr/w16s-sql14d')
end
