require "#{File.dirname(__FILE__)}/../../../Vagrantfile.core"

Environment.new(name: 'sql.local') do |environment|
  VM.new(environment, name: '14d', box: 'gusztavvargadr/w16s-sql14d') do |_14d|
    WindowsSample.new(_14d)
  end
end
