---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../../../Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: 2014x
    run_list:
      - recipe[gusztavvargadr_windows::updates]
      - recipe[gusztavvargadr_sql::2014_requirements]
      - recipe[gusztavvargadr_sql::2014_express]
  - name: 2014d
    run_list:
      - recipe[gusztavvargadr_windows::updates]
      - recipe[gusztavvargadr_sql::2014_requirements]
      - recipe[gusztavvargadr_sql::2014_developer]
