directory = File.dirname(__FILE__)
require "#{directory}/../../../../../../Berksfile.core"

gusztavvargadr_sources

gusztavvargadr_cookbook 'components', 'sql'
gusztavvargadr_cookbook 'components', 'windows'
