require "#{File.dirname(__FILE__)}/../../../Vagrantfile.core"

Environment.new(name: 'windows.local') do |environment|
  WindowsSampleVM.new(environment, name: '10', box: 'gusztavvargadr/w10e')

  WindowsSampleVM.new(environment, name: '16')
end
