driver:
  name: vagrant
  vagrantfiles:
    - ../../../../core/chef/Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w10e
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w10e
  - name: w16s
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_windows::updates]
      - recipe[gusztavvargadr_docker::requirements]
      - recipe[gusztavvargadr_docker::engine]
      - recipe[gusztavvargadr_docker::images]
    attributes:
      gusztavvargadr_docker:
        images:
          hello-world:
