---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../../../Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w10
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w10e
  - name: w16
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_windows::features]
      - recipe[gusztavvargadr_windows::chocolatey_packages]
      - recipe[gusztavvargadr_windows::native_packages]
      - recipe[gusztavvargadr_windows::files]
      - recipe[gusztavvargadr_windows::updates]
    attributes:
      gusztavvargadr_windows:
        features:
          TelnetClient:
          IIS:
        chocolatey_packages:
          nuget.commandline:
          terraform:
            version: 0.8.8
          git:
            install:
              ignorechecksum:
              params: "'/GitAndUnixToolsOnPath /NoShellIntegration'"
          powershell:
            elevated: true
        native_packages:
          .NET Core SDK:
            source: https://download.microsoft.com/download/B/9/F/B9F1AF57-C14A-4670-9973-CDF47209B5BF/dotnet-dev-win-x64.1.0.4.exe
            install:
              - /install
              - /quiet
              - /norestart
            executable: C:/Program Files/dotnet/dotnet.exe
          SQL Server Management Studio 16:
            source: https://download.microsoft.com/download/9/3/3/933EA6DD-58C5-4B78-8BEC-2DF389C72BE0/SSMS-Setup-ENU.exe
            install:
              - /install
              - /quiet
              - /norestart
            executable: C:/Program Files (x86)/Microsoft SQL Server/130/Tools/Binn/ManagementStudio/Ssms.exe
            elevated: true
        files:
          /Temp/hosts:
            source: file://C:/Windows/System32/drivers/etc/hosts
          /Temp/robots.txt:
            source: https://www.google.nl/robots.txt
