require "#{File.dirname(__FILE__)}/../../../Vagrantfile.core"

Environment.new(name: 'chef.local') do |environment|
  WindowsSampleVM.new(environment, name: 'solo') do |solo|
    ChefSoloProvisioner.new(
      solo,
      recipes: ['gusztavvargadr_windows::chocolatey_packages'],
      json: {
        'gusztavvargadr_windows' => {
          'chocolatey_packages' => {
            'nuget.commandline' => {},
          },
        },
      }
    )
  end

  WindowsSampleVM.new(environment, name: 'zero') do |zero|
    zero.vagrant.vm.synced_folder "#{File.dirname(__FILE__)}/../data", '/vagrant-data'
    ShellProvisioner.new(zero, inline: 'choco install -y chefdk git')
    ShellProvisioner.new(zero, inline: 'cd /vagrant-data/zero; berks vendor; chef-client -z --once -c client.rb -j client.json')
  end
end
