directory = File.dirname(__FILE__)
require "#{directory}/../../../Vagrantfile.core"

Environment.defaults(hostmanager: { host: true, guest: false })
Provider.defaults(memory: 2048, cpus: 2)

Environment.new(name: 'octopus.local') do |environment|
  VM.new(environment, name: 'server', box: 'gusztavvargadr/w16s-sql14d') do |server|
    HyperVProvider.new(server)
    VirtualBoxProvider.new(server)

    FileProvisioner.new(server,
      source: '/Windows/System32/drivers/etc/hosts',
      destination: '/Windows/System32/drivers/etc/hosts',
      run: 'always')

    ChefSoloProvisioner.new(server) do |chef|
      chef.vagrant.install = false
      chef.vagrant.cookbooks_path = ''

      chef.vagrant.add_recipe 'gusztavvargadr_octopus::server'
      chef.vagrant.add_recipe 'gusztavvargadr_octopus::client'
    end
  end

  VM.new(environment, name: 'tentacle-iis', box: 'gusztavvargadr/w16s-iis') do |tentacle_iis|
    HyperVProvider.new(tentacle_iis)
    VirtualBoxProvider.new(tentacle_iis)

    FileProvisioner.new(tentacle_iis,
      source: '/Windows/System32/drivers/etc/hosts',
      destination: '/Windows/System32/drivers/etc/hosts',
      run: 'always')

    ChefSoloProvisioner.new(tentacle_iis) do |chef|
      chef.vagrant.install = false
      chef.vagrant.cookbooks_path = ''

      chef.vagrant.add_recipe 'gusztavvargadr_octopus::client'
      chef.vagrant.add_recipe 'gusztavvargadr_octopus::tentacle'
    end
  end
end
