directory = File.dirname(__FILE__)
require "#{directory}/../../../Vagrantfile.core"

Environment.new(name: 'iis.local') do |environment|
  VM.new(environment, box: 'gusztavvargadr/w16s-iis') do |default|
    WindowsSample.new(default)
  end
end
