---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../../../Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: 2017c
    run_list:
      - recipe[gusztavvargadr_windows::updates]
      - recipe[gusztavvargadr_vs::2017_requirements]
      - recipe[gusztavvargadr_vs::2017_community]
  - name: 2017p
    run_list:
      - recipe[gusztavvargadr_windows::updates]
      - recipe[gusztavvargadr_vs::2017_requirements]
      - recipe[gusztavvargadr_vs::2017_professional]
