---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../core/chef/Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: u14
    driver:
      box: gusztavvargadr/u14
  - name: w16s
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s-sql14d

suites:
  - name: server
    run_list:
      - recipe[gusztavvargadr_consul::server]
    attributes:
      gusztavvargadr_consul:
        server:
          config:
            options:
              bootstrap_expect: 1
              acl_agent_token: 9ca03b8d53064957b5db56b1ddc43111
              acl_master_token: 9ca03b8d53064957b5db56b1ddc43111
