directory = File.dirname(__FILE__)
require "#{directory}/../../../Vagrantfile.core"
require "#{directory}/Vagrantfile.core"

server_count = 1
client_count = 1

environment = Environment.new(
  'consul',
  (1..server_count).map { |i| ConsulServerVM.new(i) } + (1..client_count).map { |i| ConsulClientVM.new(i) },
  encrypt: 'sUi8RtZLcKoRszrsh93wHw==',
  acl_master_token: '9ca03b8d53064957b5db56b1ddc43111',
  acl_agent_token: '9ca03b8d53064957b5db56b1ddc43111',
  acl_cli_token: '9ca03b8d53064957b5db56b1ddc43111'
)

environment.define do |config|
  config.vm.define 'cli' do |cli|
    cli.vm.synced_folder '.', '/vagrant', disabled: true

    cli_target_vm = environment.vms[0]

    cli.vm.provider 'docker' do |d|
      d.build_dir = 'docker/cli'
      d.env = {
        'CONSUL_HTTP_ADDR' => "https://#{cli_target_vm.hostname(environment)}:8500",
        'CONSUL_HTTP_TOKEN' => environment.options[:acl_cli_token],
      }
      d.create_args = ['--network', 'host']
      d.cmd = ['consul', 'members']
      d.remains_running = false
    end
  end
end
